branches:
 only:
 - master
services:
- docker
script:
- docker build -t udagram-api-feed ./udagram-api-feed
- docker tag udagram-api-feed jafcol/udagram-api-feed:v1
- docker build -t udagram-api-user ./udagram-api-user
- docker tag udagram-api-user jafcol/udagram-api-user:v1
- docker build -t udagram-frontend ./udagram-frontend
- docker tag udagram-frontend jafcol/udagram-frontend:v1
- docker build -t reverseproxy ./reverseproxy
- docker tag reverseproxy jafcol/reverseproxy:v1
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push jafcol/udagram-api-feed:v1
- docker push jafcol/udagram-api-user:v1
- docker push jafcol/udagram-frontend:v1
- docker push jafcol/reverseproxy:v1
